# Generated by Django 4.0.4 on 2022-08-06 11:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_concerts_location_en_concerts_location_pl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(max_length=255)),
                ('song_name', models.CharField(max_length=255)),
                ('audio_file', models.FilePathField(path='music/audio/')),
                ('song_img', models.ImageField(blank=True, upload_to='music/photo/')),
            ],
            options={
                'verbose_name_plural': 'Music',
            },
        ),
        migrations.AlterModelOptions(
            name='concerts',
            options={'ordering': ['-date'], 'verbose_name': 'Concert', 'verbose_name_plural': 'Concerts'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-date'], 'verbose_name_plural': 'foto'},
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_pl',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_uk',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
