# Generated by Django 4.0.4 on 2022-08-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_music_alter_concerts_options_alter_photo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='audio_file',
            field=models.FileField(upload_to='music/audio/'),
        ),
        migrations.AlterField(
            model_name='music',
            name='band_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='music',
            name='song_name',
            field=models.CharField(max_length=50),
        ),
    ]
